export const surahs = [
    { number: 1, name_en: "The Opening", name_transliteration: "Al-Fatihah", name_ar: "الفاتحة" },
    { number: 2, name_en: "The Cow", name_transliteration: "Al-Baqarah", name_ar: "البقرة" },
    { number: 3, name_en: "The Family of Imran", name_transliteration: "Aal-E-Imran", name_ar: "آل عمران" },
    { number: 4, name_en: "The Women", name_transliteration: "An-Nisa", name_ar: "النساء" },
    { number: 5, name_en: "The Table Spread", name_transliteration: "Al-Maidah", name_ar: "المائدة" },
    { number: 6, name_en: "The Cattle", name_transliteration: "Al-An'am", name_ar: "الأنعام" },
    { number: 7, name_en: "The Heights", name_transliteration: "Al-A'raf", name_ar: "الأعراف" },
    { number: 8, name_en: "The Spoils of War", name_transliteration: "Al-Anfal", name_ar: "الأنفال" },
    { number: 9, name_en: "The Repentance", name_transliteration: "At-Tawbah", name_ar: "التوبة" },
    { number: 10, name_en: "Jonah", name_transliteration: "Yunus", name_ar: "يونس" },
    { number: 11, name_en: "Hud", name_transliteration: "Hud", name_ar: "هود" },
    { number: 12, name_en: "Joseph", name_transliteration: "Yusuf", name_ar: "يوسف" },
    { number: 13, name_en: "The Thunder", name_transliteration: "Ar-Ra'd", name_ar: "الرعد" },
    { number: 14, name_en: "Abraham", name_transliteration: "Ibrahim", name_ar: "إبراهيم" },
    { number: 15, name_en: "The Rocky Tract", name_transliteration: "Al-Hijr", name_ar: "الحجر" },
    { number: 16, name_en: "The Bee", name_transliteration: "An-Nahl", name_ar: "النحل" },
    { number: 17, name_en: "The Night Journey", name_transliteration: "Al-Isra", name_ar: "الإسراء" },
    { number: 18, name_en: "The Cave", name_transliteration: "Al-Kahf", name_ar: "الكهف" },
    { number: 19, name_en: "Mary", name_transliteration: "Maryam", name_ar: "مريم" },
    { number: 20, name_en: "Ta-Ha", name_transliteration: "Ta-Ha", name_ar: "طه" },
    { number: 21, name_en: "The Prophets", name_transliteration: "Al-Anbiya", name_ar: "الأنبياء" },
    { number: 22, name_en: "The Pilgrimage", name_transliteration: "Al-Hajj", name_ar: "الحج" },
    { number: 23, name_en: "The Believers", name_transliteration: "Al-Mu'minun", name_ar: "المؤمنون" },
    { number: 24, name_en: "The Light", name_transliteration: "An-Nur", name_ar: "النور" },
    { number: 25, name_en: "The Criterion", name_transliteration: "Al-Furqan", name_ar: "الفرقان" },
    { number: 26, name_en: "The Poets", name_transliteration: "Ash-Shu'ara", name_ar: "الشعراء" },
    { number: 27, name_en: "The Ant", name_transliteration: "An-Naml", name_ar: "النمل" },
    { number: 28, name_en: "The Stories", name_transliteration: "Al-Qasas", name_ar: "القصص" },
    { number: 29, name_en: "The Spider", name_transliteration: "Al-Ankabut", name_ar: "العنكبوت" },
    { number: 30, name_en: "The Romans", name_transliteration: "Ar-Rum", name_ar: "الروم" },
    { number: 31, name_en: "Luqman", name_transliteration: "Luqman", name_ar: "لقمان" },
    { number: 32, name_en: "The Prostration", name_transliteration: "As-Sajda", name_ar: "السجدة" },
    { number: 33, name_en: "The Coalition", name_transliteration: "Al-Ahzab", name_ar: "الأحزاب" },
    { number: 34, name_en: "Sheba", name_transliteration: "Saba", name_ar: "سبأ" },
    { number: 35, name_en: "The Originator", name_transliteration: "Fatir", name_ar: "فاطر" },
    { number: 36, name_en: "Yaseen", name_transliteration: "Yaseen", name_ar: "يس" },
    { number: 37, name_en: "The Rangers", name_transliteration: "As-Saffat", name_ar: "الصافات" },
    { number: 38, name_en: "Sad", name_transliteration: "Sad", name_ar: "ص" },
    { number: 39, name_en: "The Troops", name_transliteration: "Az-Zumar", name_ar: "الزمر" },
    { number: 40, name_en: "The Forgiver", name_transliteration: "Ghafir", name_ar: "غافر" },
    { number: 41, name_en: "Explained in Detail", name_transliteration: "Fussilat", name_ar: "فصلت" },
    { number: 42, name_en: "The Consultation", name_transliteration: "Ash-Shura", name_ar: "الشورى" },
    { number: 43, name_en: "Ornaments of Gold", name_transliteration: "Az-Zukhruf", name_ar: "الزخرف" },
    { number: 44, name_en: "The Smoke", name_transliteration: "Ad-Dukhan", name_ar: "الدخان" },
    { number: 45, name_en: "The Kneeling", name_transliteration: "Al-Jatsiyah", name_ar: "الجاثية" },
    { number: 46, name_en: "The Sandhills", name_transliteration: "Al-Ahqaf", name_ar: "الأحقاف" },
    { number: 47, name_en: "Muhammad", name_transliteration: "Muhammad", name_ar: "محمد" },
    { number: 48, name_en: "The Victory", name_transliteration: "Al-Fath", name_ar: "الفتح" },
    { number: 49, name_en: "The Rooms", name_transliteration: "Al-Hujurat", name_ar: "الحجرات" },
    { number: 50, name_en: "Qaf", name_transliteration: "Qaf", name_ar: "ق" },
    { number: 51, name_en: "The Scatterers", name_transliteration: "Adh-Dhariyat", name_ar: "الذاريات" },
    { number: 52, name_en: "The Mount", name_transliteration: "At-Tur", name_ar: "الطور" },
    { number: 53, name_en: "The Star", name_transliteration: "An-Najm", name_ar: "النجم" },
    { number: 54, name_en: "The Moon", name_transliteration: "Al-Qamar", name_ar: "القمر" },
    { number: 55, name_en: "The Beneficent", name_transliteration: "Ar-Rahman", name_ar: "الرحمن" },
    { number: 56, name_en: "The Event", name_transliteration: "Al-Waqi'a", name_ar: "الواقعة" },
    { number: 57, name_en: "The Iron", name_transliteration: "Al-Hadid", name_ar: "الحديد" },
    { number: 58, name_en: "The Pleading Woman", name_transliteration: "Al-Mujadila", name_ar: "المجادلة" },
    { number: 59, name_en: "The Exile", name_transliteration: "Al-Hashr", name_ar: "الحشر" },
    { number: 60, name_en: "The Woman Who Is Examined", name_transliteration: "Al-Mumtahanah", name_ar: "الممتحنة" },
    { number: 61, name_en: "The Ranks", name_transliteration: "As-Saff", name_ar: "الصف" },
    { number: 62, name_en: "The Congregation", name_transliteration: "Al-Jumu'a", name_ar: "الجمعة" },
    { number: 63, name_en: "The Hyprocrites", name_transliteration: "Al-Munafiqun", name_ar: "المنافقون" },
    { number: 64, name_en: "The Manifestation of Losses", name_transliteration: "At-Taghabun", name_ar: "التغابن" },
    { number: 65, name_en: "The Divorce", name_transliteration: "At-Talaq", name_ar: "الطلاق" },
    { number: 66, name_en: "The Prohibition", name_transliteration: "At-Tahrim", name_ar: "التحريم" },
    { number: 67, name_en: "The Kingdom", name_transliteration: "Al-Mulk", name_ar: "الملك" },
    { number: 68, name_en: "The Pen", name_transliteration: "Al-Qalam", name_ar: "القلم" },
    { number: 69, name_en: "The Sure Truth", name_transliteration: "Al-Haqqah", name_ar: "الحاقة" },
    { number: 70, name_en: "The Ways of Ascent", name_transliteration: "Al-Ma'arij", name_ar: "المعارج" },
    { number: 71, name_en: "Noah", name_transliteration: "Nuh", name_ar: "نوح" },
    { number: 72, name_en: "The Jinn", name_transliteration: "Al-Jinn", name_ar: "الجن" },
    { number: 73, name_en: "The One Covering Himself", name_transliteration: "Al-Muzzammil", name_ar: "المزمل" },
    { number: 74, name_en: "The One Wrapping Himself Up", name_transliteration: "Al-Muddathir", name_ar: "المدثر" },
    { number: 75, name_en: "The Resurrection", name_transliteration: "Al-Qiyamah", name_ar: "القيامة" },
    { number: 76, name_en: "The Man", name_transliteration: "Al-Insan", name_ar: "الإنسان" },
    { number: 77, name_en: "Those Sent Forth", name_transliteration: "Al-Mursalat", name_ar: "المرسلات" },
    { number: 78, name_en: "The News", name_transliteration: "An-Naba", name_ar: "النبأ" },
    { number: 79, name_en: "The Who Pulls Out", name_transliteration: "An-Nazi'at", name_ar: "النازعات" },
    { number: 80, name_en: "He Frowned", name_transliteration: "Abasa", name_ar: "عبس" },
    { number: 81, name_en: "The Overthrowing", name_transliteration: "At-Takwir", name_ar: "التكوير" },
    { number: 82, name_en: "The Cleaving", name_transliteration: "Al-Infitar", name_ar: "الإنفطار" },
    { number: 83, name_en: "The Defrauding", name_transliteration: "Al-Mutaffifin", name_ar: "المطففين" },
    { number: 84, name_en: "The Splitting Open", name_transliteration: "Al-Inshiqaq", name_ar: "الإنشقاق" },
    { number: 85, name_en: "The Constellations", name_transliteration: "Al-Burooj", name_ar: "البروج" },
    { number: 86, name_en: "The Nightly Comer", name_transliteration: "At-Tariq", name_ar: "الطارق" },
    { number: 87, name_en: "The Most High", name_transliteration: "Al-Ala", name_ar: "الأعلى" },
    { number: 88, name_en: "The Overwhelming", name_transliteration: "Al-Ghashiyah", name_ar: "الغاشية" },
    { number: 89, name_en: "The Dawn", name_transliteration: "Al-Fajr", name_ar: "الفجر" },
    { number: 90, name_en: "The City", name_transliteration: "Al-Balad", name_ar: "البلد" },
    { number: 91, name_en: "The Sun", name_transliteration: "Ash-Shams", name_ar: "الشمس" },
    { number: 92, name_en: "The Night", name_transliteration: "Al-Lail", name_ar: "الليل" },
    { number: 93, name_en: "The Morning Hours", name_transliteration: "Ad-Duhaa", name_ar: "الضحى" },
    { number: 94, name_en: "The Relief", name_transliteration: "Ash-Sharh", name_ar: "الشرح" },
    { number: 95, name_en: "The Fig", name_transliteration: "At-Tin", name_ar: "التين" },
    { number: 96, name_en: "The Clot", name_transliteration: "Al-Alaq", name_ar: "العلق" },
    { number: 97, name_en: "The Power", name_transliteration: "Al-Qadr", name_ar: "القدر" },
    { number: 98, name_en: "The Clear Proof", name_transliteration: "Al-Bayyinah", name_ar: "البينة" },
    { number: 99, name_en: "The Earthquake", name_transliteration: "Az-Zalzalah", name_ar: "الزلزلة" },
    { number: 100, name_en: "The Runners", name_transliteration: "Al-Adiyat", name_ar: "العاديات" },
    { number: 101, name_en: "The Calamity", name_transliteration: "Al-Qari'ah", name_ar: "القارعة" },
    { number: 102, name_en: "The Rivalry in World Increase", name_transliteration: "At-Takathur", name_ar: "التكاثر" },
    { number: 103, name_en: "The Time", name_transliteration: "Al-Asr", name_ar: "العصر" },
    { number: 104, name_en: "The Slanderer", name_transliteration: "Al-Humazah", name_ar: "الهمزة" },
    { number: 105, name_en: "The Elephant", name_transliteration: "Al-Fil", name_ar: "الفيل" },
    { number: 106, name_en: "Quraysh", name_transliteration: "Quraish", name_ar: "قريش" },
    { number: 107, name_en: "Acts of Kindness", name_transliteration: "Al-Ma'un", name_ar: "الماعون" },
    { number: 108, name_en: "The Abundance", name_transliteration: "Al-Kawthar", name_ar: "الكوثر" },
    { number: 109, name_en: "The Disbelievers", name_transliteration: "Al-Kafirun", name_ar: "الكافرون" },
    { number: 110, name_en: "The Help", name_transliteration: "An-Nasr", name_ar: "النصر" },
    { number: 111, name_en: "The Palm Fiber", name_transliteration: "Al-Masad", name_ar: "المسد" },
    { number: 112, name_en: "The Unity", name_transliteration: "Al-Ikhlas", name_ar: "الإخلاص" },
    { number: 113, name_en: "The Dawn", name_transliteration: "Al-Falaq", name_ar: "الفلق" },
    { number: 114, name_en: "The Mankind", name_transliteration: "An-Nas", name_ar: "الناس" }
  ];
  